[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "KHTN-THCS"
version = "0.1.0"
description = "Kho luu tru tai lieu - KHTN THCS"
readme = "README.md"
authors = [ { name = "thaydang" } ]
license = { text = "MIT" }
